dist: trusty
os:
  - linux

language: node_js
node_js:
  - '9'
  - '8'

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - npm test
  - npm run test:npm && echo 'Npm packing test is passed'

before_deploy:
  - npm run dist

deploy:
  provider: npm
  email: zixia@zixia.net
  api_key: "$NPM_TOKEN"
  skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
