dist: trusty
os:
  - linux

language: node_js
node_js:
  - '7'
  - '8'

before_deploy:
  - npm version
  - npm run dist
  - npm run test:npm

deploy:
  provider: npm
  email: zixia@zixia.net
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
